### ISSUE TITLE
Hack to force kubelet metrics scraping on http did not work on 1.6.10 

### ISSUE THREAD

**Issue by t-bzhan** [Adeelku/aks-prometheus#2]
It seems that the plain http port on 10255 has been deactivated in latest AKS change: https://github.com/Azure/AKS/blob/master/CHANGELOG.md#release-2020-01-27

Forcing kubelet metrics scraping on http will make the prometheus target down with the message "Connection refused"
You can see more discussions at: https://github.com/Azure/AKS/issues/1601

Removing below statements in prometheus_values.yaml file make it works with version 1.6.10
```
# Forcing Kubelet metrics scraping on http 
kubelet:
  enabled: true
  serviceMonitor:
    https: false
```
